version: '3'
services:

  frontend:
    
    build:
      dockerfile: ./apps/frontend/Dockerfile
      target: development
      context: .
    command: npm run serve:frontend-app
    ports:
      - "4200:4200"
    
    expose:
      - 4200
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_PATH=http://localhost:3000
      - NEXT_PUBLIC_WEBSOCKETS_URL=websockets:3001
    depends_on:
      - backend

  backend:
    build:
      dockerfile: ./apps/backend/Dockerfile
      target: development
      context: .
    command: npm run dev:backend
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/clickvote
      - JWT_SECRET=sdlkfjsdsfgdsfgdkljfhfewiehw!?@#!@$!@$asdasd
      - FRONT_END_URL=http://127.0.0.1:4200
      - PASSWORD_ENCRYPTION=sdfgsdgdsgdsfgsdffasdfas
      - IV_KEY=a1b2c3d4e5f6g7dsgdsgh8a1b2c3d4e5f6g7h8
      - SUBSTACK_NEWSLETTER_URL=https://newsletter.clickvote.dev
    depends_on:
      - redis
      - mongo

  websockets:
    
    build:
      dockerfile: ./apps/websockets/Dockerfile
      target: development
      context: .
    command: npm run dev:websockets
    ports:
      - "3001:3001"
    
    expose:
      - 3001
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - TOKEN_KEY=adfgdasfgasgagsadgas
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/clickvote
    depends_on:
      - mongo
      - redis
      
  consumers:
    
    build:
      dockerfile: ./apps/consumers/Dockerfile
      target: development
      context: .
    command: npm run dev:consumers
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/clickvote
    depends_on:
      - mongo
      - redis
      
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes: 
      - clickvote-redis-data:/data

  mongo:
    image: mongo:latest
    ports:
      - 27027:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_DATABASE=clickvote
    volumes:
      - clickvote-mongo-data:/data

volumes:
  clickvote-redis-data:
  clickvote-mongo-data:
